version: "3.8"

services:
  bind9:
    container_name: bind9
    image: dmachard/bind9:9.18.24-r1
    volumes:
      - ./conf:/etc/bind/
    ports:
      - "5354:53/udp"
      - "5354:53/tcp"
    restart: always
