name: Publish

on:
  release:
    types: [published]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        cd ${{ github.event.release.tag_name }}/
        docker build . --file Dockerfile -t bind9

    - name: Tag image
      run: |
        docker tag bind9 dmachard/bind9:${{ github.event.release.tag_name }}
        docker tag bind9 dmachard/bind9:latest

    - name: Upload to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push dmachard/bind9:${{ github.event.release.tag_name }}
        docker push dmachard/bind9:latest
